config/routes.rb
Ishibashi::Application.routes.draw do
  get 'kitaguchi', :to => 'kitaguchi#index'

  get 'shelfs/show/:id',
    :controller => :user_products, :action => :show

  resources :keywords
  resources :products, :only => [:show]
  get 'products/to_amazon/:id' => 'products#to_amazon'
  get 'products/to_rakuten/:id' => 'products#to_rakuten'

  resources :user_products

  get 'users/feeds/:id.:format',
    :controller => 'users',
    :to => 'users#feeds'

  get 'users/:domain_name/:screen_name',
    :controller => 'users',
    :to => 'users#show',
    :constraints => {:domain_name => /(.*?)/}

  get 'users/:action',
    :controller => 'users'
  patch 'users/update',
    :to => 'users#update'
  post 'users/update', :to => 'users#update'

  get 'users',
    :controller => 'users',
    :to => 'users#index'

  root 'welcome#index'

end

app/models/keyword.rb
class Keyword < ActiveRecord::Base
  FTS_TARGETS = [:title, :authors, :manufacturer].
    flat_map{|s| ["a_#{s}", "r_#{s}"] }.
    map(&:to_sym)

  has_many :keyword_products
  has_many :user_keywords
  after_save :initial_search

  validates :value, :presence => true

  def amazon_search(page = 1)
    pages = 0
    results = []
    products = []

    begin
      pages, results = AmazonEcs.search(value, category, page)
    rescue Amazon::RequestError
      # do nothing
    rescue => e
      logger.error e
    end

    results.each do |result|
      Product.transaction do
        product = Product.where(:ean => result[:ean].to_s).first
        product = Product.new if product.nil?
        product.update_with_amazon(result)
        product.save
        products.push(product)
      end
    end

    return pages, products
  end

  def rakuten_search(page = 1)
    pages = 0
    results = []
    products = []

    begin
      pages, results = RakutenBooks::search(value, category, page)

    rescue => e
      logger.error e
    end

    results.each do |result|
      Product.transaction do
        product = Product.where(:ean => result[:ean].to_s).first
        product = Product.new if product.nil?
        product.update_with_rakuten_books(result)
        product.save
        products.push(product)
      end
    end

    return page, products
  end

  def search(page = 1)
    # なんかの間違いで空文字列が渡された場合は抜ける
    return [0, []] if value.blank?

    # クエリ組み立て
    begin
      keywords = Shellwords.shellwords(value)
    rescue ArgumentError
      keywords = [value]
    end
    # キーワードをGroongaのクエリ用にエスケープ
    keywords = keywords.map {|k| k.split(//).map{|c| ({'"' => '\\"', '\\' => '\\\\'})[c] || c }.join }.map{|k| "\"#{k}\"" }

    products = Product.where('fulltext @@ ?', keywords.join(' '))

    pages = (products.count / 20.0).ceil
    products = products.order('release_date desc').
      offset((page - 1) * 20).
      limit(20)

    [pages, products]
  end

  private
  def initial_search
    amazon_search
    pages, products = search
    products.each do |product|
      keyword_products.create(:product_id => product.id)
    end
  end
end

app/controllers/keywords_controller.rb
class KeywordsController < ApplicationController
  before_filter :login_required

  # GET /keywords
  # GET /keywords.json
  def index
    @user_keywords = @login_user.user_keywords.includes(:keyword).group_by{|u_k| u_k.keyword.category}
  end

  # POST /keywords
  # POST /keywords.json
  def create
    Keyword.transaction do
      @keyword = Keyword.where(:value => params[:keyword][:value], :category => params[:keyword][:category]).first
      if @keyword.blank?
        @keyword = Keyword.new(params[:keyword].permit(:value, :category))
        @keyword.save
      end

      if @keyword.user_keywords.where(:user_id => @login_user.id).count > 0
        forbidden
      else
        @user_keyword = @keyword.user_keywords.create(:user_id => @login_user.id)
      end
    end
  end

  # DELETE /keywords/1
  # DELETE /keywords/1.json
  def destroy
    UserKeyword.transaction do
      begin
        @user_keyword = @login_user.user_keywords.find(params[:id])
        @keyword = @user_keyword.keyword
        @user_keyword.destroy
        @keyword.destroy if @keyword.user_keywords.count == 0

      rescue ActiveRecord::RecordNotFound
        missing
      end
    end
  end
end

app/helpers/keywords_helper.rb
module KeywordsHelper
end

app/views/keywords/_form.html.erb
<%= form_for(@keyword) do |f| %>
  <% if @keyword.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@keyword.errors.count, "error") %> prohibited this keyword from being saved:</h2>

      <ul>
      <% @keyword.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/keywords/_user_keyword.html.erb
<li data-id="<%= user_keyword.id %>">
  <div class="value">
    <%= user_keyword.keyword.value %>
  </div>

  <div class="buttons">
    <button class="mdl-button mdl-js-button mdl-button--icon delete" data-id="<%= user_keyword.id %>">
      <i class="material-icons">delete</i>
    </button>
  </div>
</li>

app/views/keywords/_user_keyword_modal.html.erb
<div class="preview modal" style="display: none; z-index: 1000;" id="preview-<%= user_keyword_modal.id %>" data-id="<%= user_keyword_modal.id %>">
  <div class="modal-inner">
    <div class="fill-white card">
      <div class="header fill-blue text-white">
        <%= user_keyword_modal.keyword.value %>
      </div>

      <div class="body">
        <ul class="product-list">
          <%= render :partial => 'products/list_element.html.erb', :collection => user_keyword_modal.keyword.keyword_products[0, 3].map{|kp| kp.product } %>
        </ul>
      </div>

      <div class="footer">
        <div class="left"></div>
        <div class="right">
          <%= link_to "#",
            :class => 'button fill-blue text-white close' do %>
            <i class="icon icon-cross"></i>
            閉じる
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/keywords/edit.html.erb
<h1>Editing keyword</h1>

<%= render 'form' %>

<%= link_to 'Show', @keyword %> |
<%= link_to 'Back', keywords_path %>

app/views/keywords/index.html.erb
<%
  @title = "キーワード一覧・編集"
  categories = {'books' => '本', 'dvd' => 'DVD/ブルーレイ', 'music' => '音楽CD', 'software' => 'PCソフト', 'videogames' => 'TVゲーム'}
%>

<h2>キーワード</h2>

<ul class="keyword-fields">
  <% categories.each do |id, title| %>
    <li id="<%= id %>">
      <h3><%= title %></h3>
      <ul class="keywords">
        <%= render :partial => 'user_keyword', :collection => (@user_keywords[id] || []) %>
      </ul>

      <%= form_for(Keyword.new(:category => id), :format => :json) do |f| %>
        <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
          <%= f.text_field :value, :class => 'mdl-textfield__input' %>
          <%= f.label :value, 'キーワード', :class => 'mdl-textfield__label' %>
          <%= f.hidden_field :category %>
        </div>
        <div class="buttons">
          <button class="mdl-button mdl-js-button mdl-button--icon">
            <i class="material-icons">add</i>
          </button>
        </div>
      <% end %>
    </li>
  <% end %>
</ul>

<div>
  <h2>その他の設定</h2>
  <%= form_for @login_user, :url => {:controller => :users, :action => :update}, :html => {:id => 'user-settings'} do |f| %>
    <div>
      ユーザページを非公開にする
      <%= f.label :private, :class => 'mdl-switch mdl-js-switch mdl-js-ripple-effect' do %>
        <%= f.check_box :private, {:class => 'mdl-switch__input'} %>
        <span class="mdl-switch__label"></span>
      <% end %>
    </div>

    <div>
      iCalendar、RSSフィードをランダムなURLで出力する
      <%= f.label :random_url, :class => 'mdl-switch mdl-js-switch mdl-js-ripple-effect' do %>
        <%= f.check_box :random_url, {:class => 'mdl-switch__input'} %>
        <span class="mdl-switch__label"></span>
      <% end %>
    </div>
  <% end %>
</div>

app/views/keywords/new.html.erb
<h1>New keyword</h1>

<%= render 'form' %>

<%= link_to 'Back', keywords_path %>

app/views/keywords/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_keyword_path(@keyword) %> |
<%= link_to 'Back', keywords_path %>