config/routes.rb
Ishibashi::Application.routes.draw do
  get 'kitaguchi', :to => 'kitaguchi#index'

  get 'shelfs/show/:id',
    :controller => :user_products, :action => :show

  resources :keywords
  resources :products, :only => [:show]
  get 'products/to_amazon/:id' => 'products#to_amazon'
  get 'products/to_rakuten/:id' => 'products#to_rakuten'

  resources :user_products

  get 'users/feeds/:id.:format',
    :controller => 'users',
    :to => 'users#feeds'

  get 'users/:domain_name/:screen_name',
    :controller => 'users',
    :to => 'users#show',
    :constraints => {:domain_name => /(.*?)/}

  get 'users/:action',
    :controller => 'users'
  patch 'users/update',
    :to => 'users#update'
  post 'users/update', :to => 'users#update'

  get 'users',
    :controller => 'users',
    :to => 'users#index'

  root 'welcome#index'

end

app/models/product.rb
# coding: utf-8
class Product < ActiveRecord::Base
  has_many :keyword_products
  has_many :user_products

  before_save :merge_data
  before_save :update_fulltext

  def update_with_amazon(data = nil)
    data = AmazonEcs.get(self.ean) if data.nil?

    if data.present?
      ['title', 'manufacturer', 'image_medium', 'image_small', 'url', 'release_date', 'release_date_fixed'].each do |key|
        self.send("a_#{key}=", data["a_#{key}".to_sym])
      end

      self.a_authors = data[:a_authors]
      self.category = data[:category]
      self.ean = data[:ean]
    end
  end

  def update_with_rakuten_books(data = nil)
    data = RakutenBooks.get(self.ean) if data.nil?

    if data.present?
      ['title', 'authors', 'manufacturer', 'image_medium', 'image_small', 'url', 'release_date'].each do |key|
        self.send("r_#{key}=", data["r_#{key}".to_sym])
      end

      self.ean = data[:ean]
      self.category = data[:category]
    end
  end

  # アクセサ
  def authors
    if a_authors.present?
      a_authors
    else
      r_authors
    end
  end

  def manufacturer
    a_manufacturer || r_manufacturer
  end

  def title
    a_title || r_title
  end

  def image_medium
    uri = a_image_medium || r_image_medium
    uri.sub('ecx.images-amazon.com', 'images-na.ssl-images-amazon.com').
      sub('http://', 'https://') if uri
  end

  def image_small
    uri = a_image_small || r_image_small
    uri.sub('ecx.images-amazon.com', 'images-na.ssl-images-amazon.com').
      sub('http://', 'https://') if uri
  end

  #関連商品を返す
  def related_products
    return @related_products unless @related_products.nil?

    keyword = keyword_products.
      map {|kp| kp.keyword if kp.keyword.present? }.
      compact.
      sort{|a, b| b.user_keywords.count <=> a.user_keywords.count }.
      first

    if keyword.present?
      ret = keyword.keyword_products.
        includes(:product).
        order("products.release_date desc").
        limit(5).
        map {|kp| kp.product unless kp.product == self }.
        compact[0, 4]
    end

    @related_products = ret
    return ret || []
  end

  private
  # 発売日をマージする
  def merge_data
    if a_release_date.present?
      if a_release_date_fixed
        self.release_date = a_release_date
      else
        if r_release_date.present?
          self.release_date = r_release_date
        else
          self.release_date = a_release_date
        end
      end
    else
      self.release_date = r_release_date
    end
  end

  def update_fulltext
    self.fulltext = ::Keyword::FTS_TARGETS.flat_map{|c| self.send(c) }.join("\n")
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  # GET /products/1
  # GET /products/1.json
  def show
    if params[:ean].present?
      @products = Product.where(:ean => params[:ean])
    end
    @product = Product.where(:ean => params[:id]).first
  end

  def to_amazon
    show
    redirect_to @product.a_url
  end

  def to_rakuten
    show
    redirect_to @product.r_url
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/_list.html.erb
<ul class="product-list">
  <% user_products.each do |user_product| %>
    <%= render(:layout => 'products/list_element', :locals => {:list_element => user_product.product}) do %>
      <% if @user == @login_user %>
        <div class="tags">
          <% shelf_item = shelf_items.find{|item| item.product_id == user_product.product.id } %>
          <ul>
            <% if shelf_item.present? %>
              <% shelf_item.tags.each do |tag| %>
                <li>
                  <%= link_to :controller => :user_products, :action => :show, :id => @login_user.id, :keyword => tag do %>
                    <i class="icon icon-tag"></i>
                    <span><%= tag %></span>
                  <% end %>
                </li>
              <% end %>
            <% end %>
          </ul>
        </div>

        <div class="buttons-margin"></div>
        <div class="buttons">
          <% if shelf_item.present? %>
            <%= form_for shelf_item do %>
            <% end %>
          <% end %>
          <button class="mdl-button mdl-js-button mdl-button--icon ignore button" data-product-id="<%= user_product.product.id %>">
            <i class="material-icons">delete</i>
          </button>

          <button class="mdl-button mdl-js-button mdl-button--icon tag button" data-modal="product-<%= user_product.product.id %>">
            <i class="material-icons">bookmark</i>
          </button>
        </div>
      <% end %>
    <% end %>
  <% end %>
</ul>

<script id="tags-template" type="text/x-jquery-tmpl">
  <li>
    <%= link_to "${link}" do %>
      <span>${value}</span>
    <% end %>
  </li>
</script>

<% user_products.each do |user_product| %>
  <% product = user_product.product %>
  <dialog class="product modal mdl-dialog" id="product-<%= product.id %>" data-id="<%= product.id %>">
    <h4 class="mdl-dialog__title"><%= product.title %></h4>
    <div class="mdl-dialog__content">
      <%= form_for UserProduct.new do %>
        <%
          shelf_item = shelf_items.find{|item| item.product_id == product.id }
          tags = []
          tags = shelf_item.tags if shelf_item.present?
          tags_str = ''
          tags_str = "[#{tags.join('][')}]" unless tags.blank?
        %>
        <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
          <%= text_field_tag 'tags', tags_str, :id => "tags-#{product.id}", :class => 'mdl-textfield__input' %>
          <%= label_tag "tags-#{product.id}", 'タグ', :class => 'mdl-textfield__label' %>
        </div>
        <ul class="tag-selector">
          <% @user.tags.to_a.sort{|a,b| b.last <=> a.last }.map{|e| e.first }[0, 20].each do |tag| %>
            <li class="<%= 'selected' if tags.include?(tag) %>">
              <span><%= tag %></span>
            </li>
          <% end %>
        </ul>
      <% end %>
    </div>

    <div class="mdl-dialog__actions">
      <button type="button" class="mdl-button button close tags-update">更新</button>
      <button type="button" class="mdl-button close">キャンセル</button>
    </div>
  </dialog>
<% end %>

<script id="tag-selector-template" type="text/x-jquery-tmpl">
  <li>
    <span>${value}</span>
  </li>
</script>

app/views/products/_list_element.html.erb
<li id="product_<%= list_element.id %>">
  <div class="thumbnail">
    <%= link_to product_url(:id => list_element.ean) do %>
      <% if list_element.image_small.present? %>
        <%= image_tag(list_element.image_small, :alt => list_element.title) %>
      <% else %>
        <%= image_tag('dummy_small.png', :alt => list_element.title) %>
      <% end %>
    <% end %>
  </div>

  <div class="details">
    <div class="title">
      <%= link_to list_element.title, product_url(:id => list_element.ean) %>
    </div>

    <table>
      <% if list_element.authors.present? %>
        <tr>
          <th><%= author_label list_element.category %></th>
          <td>
            <ul class="authors">
              <% list_element.authors.each do |author| %>
                <li>
                  <%= author %>
                </li>
              <% end %>
            </ul>
          </td>
        </tr>
      <% end %>

      <tr>
        <th><%= maker_label list_element.category %></th>
        <td><%= list_element.manufacturer %></td>
      </tr>

      <tr>
        <th>発売日</th>
        <td>
          <%= display_time list_element %>
          <%= countdown(list_element.release_date) if list_element.a_release_date_fixed %>
        </td>
      </tr>
    </table>

    <ul class="store-link">
      <% if list_element.a_url.present? %>
        <li>
          <%= link_to list_element.a_url do %>
            <i class="icon icon-cart"></i>
            Amazon.co.jp
          <% end %>
        </li>
      <% end %>
      <% if list_element.r_url.present? %>
        <li>
          <%= link_to list_element.r_url do %>
            <i class="icon icon-cart"></i>
            楽天ブックス
          <% end %>
        </li>
      <% end %>
    </ul>

    <%= yield if block_given?%>
  </div>
</li>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<% @title = @product.title %>

<div class="primary-product">
  <div class="thumbnail">
    <%= link_to product_path(:id => @product.ean) do %>
      <% if @product.image_small.present? %>
        <%= image_tag(@product.image_medium, :alt => @product.title) %>
      <% else %>
        <%= image_tag('dummy_medium.png', :alt => @product.title) %>
      <% end %>
    <% end %>
  </div>

  <div class="details">
    <h2><%= link_to @product.title, product_path(:id => @product.ean) %></h2>

    <table>
      <% if @product.authors.present? %>
        <tr>
          <th><%= author_label @product.category %></th>
          <td>
            <ul class="authors">
              <% @product.authors.each do |author| %>
                <li>
                  <%= author %>
                </li>
              <% end %>
            </ul>
          </td>
        </tr>
      <% end %>

      <tr>
        <th><%= maker_label @product.category %></th>
        <td><%= @product.manufacturer %></td>
      </tr>

      <tr>
        <th>発売日</th>
        <td>
          <%= display_time @product %>
          <%= countdown(@product.release_date) if @product.a_release_date_fixed %>
        </td>
      </tr>
    </table>

    <ul class="store-link">
      <% if @product.a_url.present? %>
        <li>
          <%= link_to @product.a_url do %>
            <i class="icon icon-cart"></i>
            Amazon.co.jp
          <% end %>
        </li>
      <% end %>
      <% if @product.r_url.present? %>
        <li>
          <%= link_to @product.r_url do %>
            <i class="icon icon-cart"></i>
            楽天ブックス
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

<% if @products.present? %>
  <div>
    <ul class="product-list">
      <%= render :partial => 'products/list_element', :collection => @products %>
    </ul>
  </div>
  <% @title += ' ほか' %>
<% end %>

<% content_for(:head) do %>
  <meta name="twitter:card" content="summary">
  <meta name="twitter:site" content="@yumenosoranet">
  <meta name="twitter:title" content="<%= @title %>: <%= Ishibashi::Application.config.title %>">
  <meta name="twitter:description" content="<%= @product.title %> は<%= display_time @product %> 発売です。">
  <meta name="twitter:image" content="<%= @product.image_medium || asset_url('dummy_medium.png') %>">
<% end %>